
DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
id INT AUTO_INCREMENT  PRIMARY KEY,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
age INT NOT NULL,
gender VARCHAR(6) NOT NULL
);
